<table  border="0" cellpadding="20" cellspacing="20" height="100%" width="100%" id="bodyTable" style="vertical-align: middle;" >
    <tr>
        <th>Nombre</th><td><?php echo $this->object->getNombre(); ?></td>
    </tr>
    
     <tr>
        <th>Email</th><td><?php echo $this->object->getEmail(); ?></td>
    </tr>
    
     <tr>
        <th>Consulta</th><td><?php echo $this->object->getTexto(); ?></td>
    </tr>
    
</table>
