<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>" id="side-menu">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a 
                    class="nav-header" 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                        <?php if ($page->get("icon") !== ""): ?>
                        <i class="<?php echo $page->get("icon"); ?>"></i>
                    <?php endif; ?>
                    <?php echo $page->getLabel() ?>


                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="<?php if ($page->isActive(true)) echo ' active' ?>">
                    <a   href="#">
                        <?php if ($page->get("icon") !== ""): ?>
                            <span class="<?php echo $page->get("icon"); ?>"></span>
                        <?php endif; ?>
                        <?php echo $page->getLabel() ?>
                        <span class="fa arrow"></span>
                    </a>
                    <ul class="nav nav-second-level">
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php $has3Children = $child->hasPages() ?>
                            <?php if (!$has3Children): ?>
                                <?php if ($child->get("separator") === true): ?>
                                    <li class="divider"></li>
                                    <?php
                                    continue;
                                endif;
                                ?>
                                <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                                    <a 
                                        href="<?php echo $child->getHref() ?>"
                                        <?php if ($child->getTarget() != ""): ?>
                                            target="<?php echo $child->getTarget(); ?>"
                                        <?php endif; ?> >
                                            <?php if ($child->get("icon") !== ""): ?>
                                            <span class="<?php echo $child->get("icon"); ?>"></span>
                                        <?php endif; ?>
                                        <?php echo $child->getLabel() ?>
                                    </a>
                                </li>
                            <?php else: ?>
                                <?php
                                //check if access is allowed at least one item
                                $access3 = false;
                                foreach ($child->getPages() as $child3) {
                                    if ($this->navigation()->accept($child3) && $child3->get("separator") !== true) {
                                        $access3 = true;
                                    }
                                }
                                if ($access3) :
                                    ?>




                                    <li class="<?php if ($child->isActive(true)) echo ' active' ?>">
                                        <a   href="#">
                                            <?php if ($child->get("icon") !== ""): ?>
                                                <span class="<?php echo $child->get("icon"); ?>"></span>
                                            <?php endif; ?>
                                            <?php echo $child->getLabel() ?>
                                            <span class="fa arrow"></span>
                                        </a>
                                        <ul class="nav nav-third-level">
                                            <?php foreach ($child->getPages() as $child3): ?>
                                                <?php if (!$this->navigation()->accept($child3)) continue; ?>

                                                <li<?php if ($child3->isActive()) echo ' class="active"' ?>>
                                                    <a 
                                                        href="<?php echo $child3->getHref() ?>"
                                                        <?php if ($child3->getTarget() != ""): ?>
                                                            target="<?php echo $child3->getTarget(); ?>"
                                                        <?php endif; ?> >
                                                            <?php if ($child3->get("icon") !== ""): ?>
                                                            <span class="<?php echo $child3->get("icon"); ?>"></span>
                                                        <?php endif; ?>
                                                        <?php echo $child3->getLabel() ?>
                                                    </a>
                                                </li>
                                            <?php endforeach ?>      
                                        </ul>   



















                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endforeach ?>
                    </ul>
                </li>   
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>