<?php echo $this->translate("Jenuary"); ?>
<?php echo $this->translate("February"); ?>
<?php echo $this->translate("March"); ?>
<?php echo $this->translate("April"); ?>
<?php echo $this->translate("May"); ?>
<?php echo $this->translate("June"); ?>
<?php echo $this->translate("July"); ?>
<?php echo $this->translate("August"); ?>
<?php echo $this->translate("September"); ?>
<?php echo $this->translate("October"); ?>
<?php echo $this->translate("November"); ?>
<?php echo $this->translate("December"); ?>


<?php echo $this->translate("Monday"); ?>
<?php echo $this->translate("Tuesday"); ?>
<?php echo $this->translate("Wednesday"); ?>
<?php echo $this->translate("Thursday"); ?>
<?php echo $this->translate("Friday"); ?>
<?php echo $this->translate("Saturday"); ?>
<?php echo $this->translate("Sunday"); ?>



