<!-- Le styles -->
<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/dist/css/sb-admin-2.css')
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/bower_components/bootstrap/dist/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/sb-admin-v2/bower_components/font-awesome/css/font-awesome.css')
        ->appendStylesheet($this->basePath() . '/css/custom.css')
?> 