   <?php 
   echo $this->headScript()
           ->prependFile($this->basePath() . '/lib/datetimepicker/js/bootstrap-datetimepicker.min.js')
           ->prependFile($this->basePath() . '/lib/moment/locale/es.js')
           ->prependFile($this->basePath() . '/lib/moment/moment.min.js')
           ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
                ->prependFile($this->basePath() . '/sb-admin-v2/js/sb-admin.js')
                ->prependFile($this->basePath() . '/sb-admin-v2/js/plugins/metisMenu/jquery.metisMenu.js')
                ->prependFile($this->basePath() . '/sb-admin-v2/js/bootstrap.min.js')
                ->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js', 'text/javascript')
                ;
        ?>