<div class="navbar-default sidebar" role="navigation">
    <div class="">
        
    </div>
    <div class="clearfix"></div>
  
        <div class="sidebar-nav navbar-collapse">
            <?php
            echo $this->
                    navigation('navigation')
                    ->menu()
                    ->setUlClass('nav')
                    ->setPartial('partial/navigation.phtml');
            ?>

        </div>
 
</div>