<?php
$this->headScript()->prependFile($this->basePath() . '/lib/lwtcountdown/js/jquery.lwtCountdown-1.0.js');
?>
<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/lib/lwtcountdown/style/main.css');
?> 

<br>
<div class="row" >
    <div class="e_header box-1 " >
        <div class="col-lg-8 col-md-8 col-xs-12 e_izq  "  >

            <div class="col-xs-12 e_cover nomargin" style="background:url('<?php echo $this->evento->getLugarFlyer()->getImagen(); ?>');    background-repeat: no-repeat;   background-size: 100% 100%;  background-origin: content-box; background-position: center center;">
                <div class="col-lg-6 col-md-6 col-xs-8 text-center ">
                    <h4 class="flyer-title pull-left"><?php echo $this->evento->getFecha()->format("d-m-Y"); ?></h4> 
                </div>
              
            </div>


            <div class="col-xs-12 e_photos nomargin nopadding">
                <?php $i = 0; ?>
                <table class="table table-bordered nopadding nomargin table-responsive table-condensed">
                    <tr>

                        <?php foreach ($this->evento->getLugar()->getFotos() as $foto): ?>
                            <td class="nopadding">

                                <a href="#" class="" style="margin-bottom: 0;" onclick="showImg('<?php echo $foto->getImagen(); ?>')">
                                    <img src="<?php echo $foto->getImagen(); ?>" alt="..." class="nopadding nomargin img-responsive " />
                                </a>
                            </td>
                            <?php
                            $i++;
                            if ($i > 4) {
                                break;
                            }
                            ?>
                        <?php endforeach; ?>

                    </tr>
                </table>
            </div>


        </div>



        <div class="col-lg-4 col-md-4 col-xs-12 e_der">


            <div class="e_birthday nopadding row transparent">

                <div class="text-center transparent" >
                    <h2 class="htitle"> IT's Your Birthday</h2>
                </div>



                <div class="text-center  cprofile transparent">
                    <?php if ($this->evento->getContacto()): ?>
                        <img src="http://graph.facebook.com/<?php echo $this->evento->getContacto()->getFacebookId(); ?>/picture?type=large" alt="..." style="width: 100px; height: 100px;" class="img-circle" /><span class="cname"><?php echo $this->evento->getContacto()->getFullname(); ?></span> 
                    <?php else: ?>
                        <img src="/img/profile.jpg" alt="..." style="width: 100px; height: 100px;" class="img-circle" /><span class="cname" ><?php echo $this->evento->getNombre(); ?></span> 
                    <?php endif; ?>

                </div>

                <div class="text-center transparent">
                    <h2 class="htitle">   Celebrate IT</h2>

                </div>
            </div>




            <div class="row transparent">
                <div class="col-lg-12 col-xs-12  text-center transparent">
                    <h4 class="cdireccion"><?php echo $this->evento->getLugar()->getNombre(); ?></h4>

                    <h5 class="cdireccion">Dirección: <?php echo $this->evento->getLugar()->getDireccion(); ?></h5> 

                    <h5 class="cdireccion cursor-pointer"><i class="fa fa-map-marker"></i> Mapa</h5> 
                </div>
            </div>



        </div>

    </div>
</div>



<div class="row ">
    <div  class="col-lg-8 col-xs-12 marginTop30 ">
        <div class="box-2 formato padding5">


            <?php echo nl2br($this->evento->getFormato()->getHtml()); ?>
        </div>
    </div>




    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12  text-center  vcenter marginButtom10 marginTop30 ">
        <div class=" box-2 padding5 ">
            <a class="btn btn-facebook fa fa-facebook-f" href="<?php echo $this->loginUrl; ?>"> Confirmar con Facebook</a>
        </div>
        
         <div class=" box-2 padding5 container-fluid " >
          <div class="col-lg-12 col-md-12 col-xs-12 ">
                    <div class="" style="">
                        <div id="countdown_dashboard" class="pull-right">


                            <div class="col-lg-2 col-md-2 col-xs-3 pull-right ">
                                <div class="dash seconds_dash">
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>

                                </div>
                                <div class="clearfix"></div>
                                <div class="dash_title">
                                    seconds
                                </div>

                            </div>

                            <div class="col-lg-2 col-md-2 col-xs-3 pull-right ">
                                <div class="dash minutes_dash">
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>

                                </div>
                                <div class="clearfix"></div>
                                <div class="dash_title">
                                    minutes
                                </div>

                            </div>





                            <div class="col-lg-2 col-md-2 col-xs-3 pull-right ">
                                <div class="dash hours_dash">
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>

                                </div>
                                <div class="clearfix"></div>
                                <div class="dash_title">
                                    hours
                                </div>
                            </div>

                            <div class="col-lg-2 col-md-2 col-xs-3 pull-right ">
                                <div class="dash days_dash">
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>

                                </div>
                                <div class="clearfix"></div>
                                <div class="dash_title">
                                    days
                                </div>

                            </div>



                            <div class="col-lg-2 col-md-2 col-xs-3 pull-right ">
                                <div class="dash weeks_dash">
                                    <div class="digit">0</div>
                                    <div class="digit">0</div>

                                </div>
                                <div class="clearfix"></div>
                                <div class="dash_title">
                                    weeks
                                </div>

                            </div>


                        </div>
                    </div>
                </div>
 </div>
        <div class="box-2 padding5">
            <h4 class="cursor-pointer">Invitados Confirmados</h4> 
            <?php if ($this->evento->getConfirmados()): ?>
                <div class="list-group marginButtom10 container-fluid">

                    <?php foreach ($this->evento->getConfirmados() as $contacto): ?>

                        <a href="#" class="list-group-item text-left col-xs-10 col-xs-offset-1 padding2 ">
                            <img src="http://graph.facebook.com/<?php echo $contacto->getFacebookId(); ?>/picture?type=large" alt="..." style="width: 35px; height: 35px;" class="img-rounded" />
                            <span class="cnameInvitado"><?php echo $contacto->getFullname(); ?></span> 
                        </a>

                    <?php endforeach; ?>

                </div>

            <?php endif; ?>
        </div>


        <div class="box-2 padding5" style="overflow: hidden;">
            <h4 class="cursor-pointer">Invitados</h4> 
            <div >
                <table class="table table-bordered table-condensed table-responsive" id="lista_invitados">
                    <tbody>
                    <tr>
                        <th class="col-xs-5">Nombre</th>
                        <th class="col-xs-5">Celular</th>
                    </tr>
</tbody>
                    <?php if ($this->evento->getInvitados()): ?>
                        <?php foreach ($this->evento->getInvitados() as $invitado): ?>
                            <tr>
                                <td><?php echo $invitado->getNombre(); ?></td>
                                <td><?php echo $invitado->getCelular(); ?></td

                            </tr>



                        <?php endforeach; ?>
                    <?php endif; ?>

                </table>
                <div style="overflow: hidden;">
                    
               
                <?php if ($this->formInvitado): ?>

                    <?php echo $this->partial('widget/invitado', array('form' => $this->formInvitado)); ?>

                <?php endif; ?>
                     </div>
                <br>
            </div>
        </div>



    </div>




    <div class='modal fade ' id='imgModal'>
        <div class='modal-dialog'>
            <div class='modal-content'>

                <div class='modal-body'>
                    <button type='button' class='close' data-dixsiss='modal'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>

                    <div id='imgModalContent'></div>
                </div>
            </div>
        </div>
    </div>
    <script>

        function showImg(item) {
            $('#imgModalContent').html("<div class='text-center'><img class='img-responsive' src='" + item + "'  /></div>");

            $('#imgModal').modal('show');
        }



        function addInvitado() {

            var datastring = $('#Invitado').serialize();

            $.post('/inter/invitado', datastring)
                    .done(function (data) {
                        if (data !== "error") {
                            $('#lista_invitados').append(data);
                     $('#Invitado')[0].reset();
                        }


                    });

        }


    </script>
    <script language="javascript" type="text/javascript">
        jQuery(document).ready(function () {
            $('#countdown_dashboard').countDown({
                targetDate: {
                    'day': <?php echo $this->evento->getFecha()->format("d"); ?>,
                    'month': <?php echo $this->evento->getFecha()->format("m"); ?>,
                    'year': <?php echo $this->evento->getFecha()->format("Y"); ?>,
                    'hour': 11,
                    'min': 0,
                    'sec': 0
                }
            });

        });
    </script>
