<div class=" " >
    
    <div class="col-lg-12 col-xs-12 box-2 marginTop30 ">
        
        <h2>Politicas de Privacidad</h2>
<h3>SECCIÓN 1 - ¿QUÉ HACEMOS CON TU INFORMACIÓN?</h3>

<p>Cuando generas un evento en nuestro site, como parte del proceso, nosotros recolectamos la información personal que nos

das tales como nombre, dirección y correo electrónico.

Cuando navegas en nuestro sitio, también recibimos de manera automática la dirección de protocolo de internet de tu computadora (IP)

con el fin de proporcionarnos información que nos ayuda a conocer acerca de su navegador y sistema operativo.

Email marketing: Con tu permiso, podremos enviarte correos electrónicos acerca de nuestra tienda, nuevos productos y otras actualizaciones
</p>
 
<h3>SECTION 2 - CONSENTIMIENTO</h3>

<p>
Cómo obtienen mi consentimiento?

Cuando nos provees tu información personal para completar una transacción, implicamos que aceptas la recolección y uso por esa razón específica solamente.

Si te pedimos tu información personal por una razón secundaria, como marketing, te pediremos directame tu expreso consentimiento, o te daremos la oportunidad de negarte.

¿Cómo puedo anular mi consentimiento?

Si luego de haber aceptado cambias de opinión, puedes anular tu consentimiento para que te contactemos, por la recolección, uso o divulgación de tu información, en cualquier momento, contactándonos a Info@charlyruez.com o escribiéndonos a: Palermo Nights  PARANÁ 641 , Ciudad Autónoma de Buenos Aires , AL, 1017, Argentina
</p>

<h3>SECCIÓN 3 - DIVULGACIÓN</h3>

<p>
Podemos divulgar tu información personal si se nos requiere por ley o si violas nuestros Términos de Servicio.
</p>


<h3>SECCIÓN 4 - SEGURIDAD</h3>

<p>
Para proteger tu información personal, tomamos precauciones razonables y seguimos las mejores prácticas de la industria para asegurarnos de que no haya pérdida de manera inapropiada, mal uso, acceso, divulgación, alteración o destrucción de la misma.
</p>


<h3>SECCIÓN 5 - EDAD DE CONSENTIMIENTO</h3>

<p>
Al utilizar este sitio, declaras que tienes al menos la mayoría de edad en tu estado o provincia de residencia, o que tienes la mayoría de edad en tu estado o provincia de residencia y que nos has dado tu consentimiento para permitir que cualquiera de tus dependientes menores use este sitio.
</p>

<h3>SECCIÓN 6 - CAMBIOS A ESTA POLÍTICA DE PRIVACIDAD</h3>

<p>
Nos reservamos el derecho de modificar esta política de privacidad en cualquier momento, asique por favor revísala frecuentemente.  Cambios y aclaraciones entrarán en vigencia inmediatamente después de su publicación en el sitio web.  Si hacemos cambios materiales a esta política, notificaremos aquí que ha sido actualizada, por lo que cual estás enterado de qué información recopilamos, cómo y bajo qué circunstancias, si las hubiere, la utilizamos y/o divulgamos.
</p>


<h3>PREGUNTAS E INFORMACIÓN DE CONTACTO</h3>

<p>
Si quieres: acceder, corregir, enmendar o borrar cualquier información personal que poseamos sobre ti, registrar una queja, o simplemente quieres más información contacta a nuestro Oficial de Cumplimiento de Privacidad Info@charlyruez.com o por correopostal a Palermo Nights 
</p>
</div>
 </div>
